# Generated by Django 2.0.3 on 2018-03-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ctrip',
            fields=[
                ('in_place', models.CharField(max_length=32)),
                ('inplace_pinyin', models.CharField(max_length=32)),
                ('notice', models.TextField(null=True)),
                ('title', models.CharField(max_length=32)),
                ('title_pinyin', models.CharField(max_length=100)),
                ('title_url', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=32)),
                ('place', models.CharField(max_length=50)),
                ('comment_nums', models.CharField(max_length=100)),
                ('image_urls', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mafengwo',
            fields=[
                ('in_place', models.CharField(max_length=32)),
                ('inplace_pinyin', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('title_pinyin', models.CharField(max_length=100)),
                ('title_url', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comment_nums', models.CharField(max_length=100)),
                ('comment_mains', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('name_pinyin', models.CharField(max_length=32)),
                ('image_urls', models.CharField(max_length=100)),
            ],
        ),
    ]
